MAX_STEP = 500

MAP_SIZE = BOARD_SIZE = 16
MAP_SIZE2 = MAP_SIZE * 2
VIEW_SHAPE = (1, MAP_SIZE, MAP_SIZE)

NUM_RESTAURANT = 10
NUM_CUSTOMER = 20

MAX_DELIVER_ORDER_NUM = 5
MAX_DISTRIBUTE_NUM = 20
MAX_STEP_GRAB_NUM = 10

MAX_GRAB_PER_STEP = MAX_DELIVER_ORDER_NUM

GRAB_ACTION_NUM = MAX_STEP_GRAB_NUM + 1

# [up, down, left, right, not move]
DIRECTION = [(-1, 0), (1, 0), (0, -1), (0, 1), (0, 0)]

DIRECTION_NAME = ['up', 'down', 'left', 'right', 'stay']

MOVE_ACTION_NUM = len(DIRECTION) - 1

# map type enums
MAX_GRASS = 0
MAP_ROAD = 1
MAP_RESTAURANT = 2
MAP_CUSTOMER = 3
MAP_FEATURE_NUM = 4

USE_GRAB_ACTOR = False

GRAB_MODEL_FEATURE_NUM = 42  # 2 + 10 * 4
