PLAYER0 = 'player_0'
PLAYER1 = 'player_1'

MAX_MATCH_STEP = 100
MAX_UNIT_NUM = 16

MAP_WIDTH = 24
MAP_HEIGHT = 24

CELL_UNKONWN = 0
CELL_SPACE = 1
CELL_NEBULA = 2
CELL_ASTERIOD = 3

RELIC_NB_SIZE = 5

TEAM_POINT_MASS = 100
NON_TEAM_POINT_MASS = -100

MAX_GAME_STEPS = 505
MAX_MATCH_STEPS = 100

# 0 is do nothing, 1 is move up, 2 is move right, 3 is move down, 4 is move left, 5 is sap
MOVE_ACTION_NUM = 5
