name: run_20250306_b16_r3_hide_relic
project: lux_s3
entity: pyflynn
group: luxs3_rl_0306_final
obs_space_kwargs:
  use_energy_cost_map: true
  use_single_player: false
  use_agent: false
  use_unit_energy_sum: true
  use_enemy_vision_map: true
  use_match_relic_hints: true
  use_more_game_params: true
  use_energy_trace: true
  use_futrue_map: true
  hide_relic: true
use_separate_base: false
reward_space_kwargs: {}
reward_schema: game_win_loss2
reward_shaping_params:
  use_hidden_relic_estimator: true
  energy_cost_change: 0
  match_observed: 0
  match_result: 1
  unit_kill: 0.01
  match_sap_num: 0.2
  game_win: 1
total_steps: 300000000.0
num_actors: 20
n_actor_envs: 4
unroll_length: 16
batch_size: 4
discounting: 0.999
model_arch: conv_model
n_blocks: 16
hidden_dim: 128
base_out_channels: 230
embedding_dim: 8
n_merge_layers: 1
normalize: false
sum_player_embeddings: false
use_index_select: false
rescale_value_input: true
rescale_se_input: true
kernel_size: 5
optimizer_class: Adam
optimizer_kwargs:
  lr: 5.0e-05
  eps: 0.0003
min_lr_mod: 0.01
entropy_cost: 0.0005
baseline_cost: 1.0
teacher_kl_cost: 0.001
teacher_baseline_cost: 0.0
lmb: 0.9
reduction: sum
disable_upgo_pg_loss: true
use_teacher: true
teacher_load_dir: /root/autodl-tmp/ebb/03-06/17-35-10
teacher_checkpoint_file: 040295552_weights.pt
use_mixed_precision: true
max_one_gpu_actor_num: 0
actor_device: cuda:0
learner_device: cuda:1
model_log_freq: 100
checkpoint_freq: 30
sharing_strategy: file_system
disable_wandb: false
debug: false
load_dir: /root/autodl-tmp/ebb/03-06/21-45-38
checkpoint_file: 046590464.pt
weights_only: false
n_value_warmup_batches: 0
seed: null
num_buffers: 40
ob_params: {}
clip_grads: 10.0
num_learner_threads: 1
use_shared_base: true
--config-name: null
luxs3_teacher_stage1: null
