defaults:
- override hydra/job_logging: default
- override hydra/hydra_logging: default

hydra:
  run:
    dir: /home/flynnwang/runs/ebb/${now:%m-%d}/${now:%H-%M-%S}

name: run_20250107_reverted_move_center_on_relic_node_only

r_new_observed: 0.001
r_visit_relic_nb: 0.001
r_team_point: 0.0003
r_dead_units: 0
r_match: 0.05
r_game: 0.05

## WANDB params
# The wandb project name
project: lux_s3
# The wandb user to log to
entity: pyflynn
# The wandb group for the run
group: luxs3_reverted

## ENV params
obs_space_kwargs: {}
reward_space_kwargs: {}
#reward_schema: exploration_reward
reward_schema: game_win_loss

## TRAINING params
total_steps: 3e8
num_actors: 16
n_actor_envs: 4

unroll_length: 16
# Batch must be multiple of `n_actor_envs`
batch_size: 8
discounting: 0.999

## MODEL params
model_arch: conv_model
n_blocks: 8
hidden_dim: 128
base_out_channels: 128
embedding_dim: 32
n_merge_layers: 1
normalize: False
sum_player_embeddings: False
use_index_select: False
rescale_value_input: True
rescale_se_input: True
# Conv-specific params
kernel_size: 5


## OPTIMIZER params
optimizer_class: Adam
optimizer_kwargs:
  lr: 5e-5
  # See https://arxiv.org/pdf/2105.05246.pdf
  eps: 0.0003
  #alpha: 0.9
min_lr_mod: 0.01

## LOSS params
entropy_cost: 0.0005
baseline_cost: 1.
teacher_kl_cost: 0.001
teacher_baseline_cost: 0.0
# lambda parameter for TD-lambda and UPGO losses
lmb: 0.9
reduction: sum

# Pretrained model for KL loss
use_teacher: True
teacher_load_dir: /home/flynnwang/runs/ebb/01-06/14-50-31/
teacher_checkpoint_file: 047202176_weights.pt
#teacher_load_dir: /home/flynnwang/runs/ebb/01-07/09-05-35/
#teacher_checkpoint_file: 018604544_weights.pt

# MISCELLANEOUS params
use_mixed_precision: True
max_one_gpu_actor_num: 8
actor_device: cuda:0
learner_device: cuda:1

#actor_device: cpu
#learner_device: cpu
model_log_freq: 100

# in minutes
checkpoint_freq: 20
# file_descriptor or file_system
sharing_strategy: file_system

disable_wandb: False
debug: False
#disable_wandb: True
#debug: True


#load_dir: /home/flynnwang/runs/ebb/01-06/17-46-59
#checkpoint_file: 004086784.pt
load_dir:
checkpoint_file:
#
weights_only: False
n_value_warmup_batches: 0
