defaults:


- override hydra/job_logging: default
- override hydra/hydra_logging: default

hydra:
  run:
    dir: /home/flynnwang/runs/ebb/${now:%m-%d}/${now:%H-%M-%S}

name: run_20250120_match_explore_with_relic_estimator_r1

## WANDB params
# The wandb project name
project: lux_s3
# The wandb user to log to
entity: pyflynn
# The wandb group for the run
group: luxs3_match_explore_win_loss_0120

## ENV params
obs_space_kwargs: {}
reward_space_kwargs: {}
#reward_schema: game_win_loss2
#reward_schema: shaping
reward_schema: match_explore_win_loss
reward_shaping_params:
  use_hidden_relic_estimator: True

  new_observed_down_tri: 0.0003
  new_observed_main_diag: 0.0005
  new_observed_corners: 0.001
  relic_nb: 0.001
  units_on_relic: 0.001
  team_point: 0.0003
  match_result: 1.0
  game_result: 0
  first_frozen_uints: -0.001
  stay_frozen_units: -0.0005
  dead_uints: 0
  units_position_energy_sum: 0

## TRAINING params
total_steps: 2e8
num_actors: 12
n_actor_envs: 16

unroll_length: 16
# Batch must be multiple of `n_actor_envs`
batch_size: 4

discounting: 0.999

## MODEL params
model_arch: conv_model
n_blocks: 12
hidden_dim: 128
base_out_channels: 128
embedding_dim: 32
n_merge_layers: 1
normalize: False
sum_player_embeddings: False
use_index_select: False
rescale_value_input: True
rescale_se_input: True
# Conv-specific params
kernel_size: 5


## OPTIMIZER params
optimizer_class: Adam
optimizer_kwargs:
  lr: 3e-5
  # See https://arxiv.org/pdf/2105.05246.pdf
  eps: 0.0003
  #alpha: 0.9
min_lr_mod: 0.01

## LOSS params
#entropy_cost: 6e-4
entropy_cost: 4e-3
baseline_cost: 1.
teacher_kl_cost: 1e-4
teacher_baseline_cost: 0.0
# lambda parameter for TD-lambda and UPGO losses
lmb: 0.8
#lmb: 0.9
reduction: sum


# Pretrained model for KL loss
use_teacher: False
teacher_load_dir:  /home/flynnwang/runs/ebb/01-18/11-05-57
teacher_checkpoint_file: 104282624_weights.pt

# MISCELLANEOUS params
use_mixed_precision: True
max_one_gpu_actor_num: 0
actor_device: cuda:0
learner_device: cuda:1

#actor_device: cpu
#learner_device: cpu
model_log_freq: 100

# in minutes
checkpoint_freq: 20
# file_descriptor or file_system
sharing_strategy: file_system

disable_wandb: False
debug: False
#disable_wandb: True
#debug: True

load_dir:
checkpoint_file:
#
weights_only: False
n_value_warmup_batches: 0
