defaults:


- override hydra/job_logging: default
- override hydra/hydra_logging: default

hydra:
  run:
    dir: /home/flynnwang/runs/ebb/${now:%m-%d}/${now:%H-%M-%S}

name: run_20250301_game_win_loss_r1

## WANDB params
# The wandb project name
project: lux_s3
# The wandb user to log to
entity: pyflynn
# The wandb group for the run
group: luxs3_rl_exp_0301_v3_no_upgo

## ENV params
obs_space_kwargs:
  use_energy_cost_map: True
  use_single_player: False
  use_agent: False

  use_unit_energy_sum: True
  use_enemy_vision_map: True
  use_match_relic_hints: True
  use_more_game_params: True


reward_space_kwargs: {}
reward_schema: game_win_loss2
#reward_schema: match_win_loss
use_separate_base: False

#reward_schema: match_explore_win_loss
#reward_schema: shaping_v2
reward_shaping_params:
  use_hidden_relic_estimator: True
  energy_cost_change: 0
  match_observed: 0
  match_win: 0.2
  match_result: 1
  unit_kill: 0.01

  match_sap_num: 1
  game_win: 0.1

## TRAINING params
total_steps: 2e8
num_actors: 14
n_actor_envs: 4

unroll_length: 16
# Batch must be multiple of `n_actor_envs`
batch_size: 4

discounting: 0.999

## MODEL params
model_arch: conv_model
n_blocks: 16
hidden_dim: 128
base_out_channels: 128
embedding_dim: 8
n_merge_layers: 1
normalize: False
sum_player_embeddings: False
use_index_select: False
rescale_value_input: True
rescale_se_input: True
# Conv-specific params
kernel_size: 5


## OPTIMIZER params
optimizer_class: Adam
optimizer_kwargs:
  lr: 5e-5
  #lr: 1e-5
  #lr: 5e-6
  #lr: 1e-6
  # See https://arxiv.org/pdf/2105.05246.pdf
  eps: 0.0003
  #alpha: 0.9
min_lr_mod: 0.01

## LOSS params
#entropy_cost: 2e-6
#entropy_cost: 1e-5
#entropy_cost: 1e-4
entropy_cost: 2e-4
#entropy_cost: 5e-4
#entropy_cost: 1e-3
#entropy_cost: 5e-3
#entropy_cost: 1e-2
baseline_cost: 1.
#teacher_kl_cost: 0
#teacher_kl_cost: 1e-4
#teacher_kl_cost: 5e-4
teacher_kl_cost: 1e-3
#teacher_kl_cost: 5e-3
#teacher_kl_cost: 1e-2
teacher_baseline_cost: 0.0
# lambda parameter for TD-lambda and UPGO losses
#lmb: 0.8
lmb: 0.9
reduction: sum
disable_upgo_pg_loss: True


# Pretrained model for KL loss
use_teacher: True
teacher_load_dir: /home/flynnwang/runs/ebb/03-01/23-56-37
teacher_checkpoint_file: 003204544_weights.pt
#teacher_load_dir: /home/flynnwang/runs/ebb/02-26/23-20-33
#teacher_checkpoint_file: 039125696.pt

# MISCELLANEOUS params
use_mixed_precision: True
max_one_gpu_actor_num: 0
actor_device: cuda:0
learner_device: cuda:1

#actor_device: cpu
#learner_device: cpu
model_log_freq: 100

# in minutes
checkpoint_freq: 30
# file_descriptor or file_system
sharing_strategy: file_system

disable_wandb: False
debug: False
#disable_wandb: True
#debug: True


load_dir: /home/flynnwang/runs/ebb/03-01/23-56-37
checkpoint_file: 012871616.pt
#load_dir: /home/flynnwang/runs/ebb/03-01/20-50-11
#checkpoint_file: 005604736.pt
#load_dir: /home/flynnwang/runs/ebb/03-01/16-42-31
#checkpoint_file: 005980672.pt
#load_dir: /home/flynnwang/runs/ebb/02-26/23-20-33
#checkpoint_file: 039125696.pt

weights_only: False
#weights_only: True
n_value_warmup_batches: 0
